//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackYourWorkers
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtvoreniUgovori
    {
        public string Student { get; set; }
        public string Mjesec { get; set; }
        public string NazivRadnogMjesta { get; set; }
        public string OIB { get; set; }
    }
}
