//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackYourWorkers
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadnoMjesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RadnoMjesto()
        {
            this.Ugovor = new HashSet<Ugovor>();
        }
    
        public int RadnoMjestoId { get; set; }
        public string NazivRadnogMjesta { get; set; }
        public string OpisRadnogMjesta { get; set; }
        public decimal CijenaRadnogSata { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ugovor> Ugovor { get; set; }
    }
}
