//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackYourWorkers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ugovor
    {
        public int UgovorId { get; set; }
        public int Student { get; set; }
        public string Mjesec { get; set; }
        public int RadnoMjesto { get; set; }
        public Nullable<int> BrojRadnihSati { get; set; }
        public System.DateTime DatumOtvaranja { get; set; }
        public Nullable<decimal> Iznos { get; set; }
        public Nullable<bool> Isplaceno { get; set; }
    
        public virtual RadnoMjesto RadnoMjesto1 { get; set; }
        public virtual Student Student1 { get; set; }
    }
}
